seed: 42
do_train: True
do_predict: True

output_dir: ../../output_model/esa

# golden_trigger: False 
type2id_path: ../../input/type2id.json
role2id_path: ../../input/role2id.json
train_file: /input_4fold/4fold_train.json
validation_file: /input_4fold/4fold_valid.json
test_file: /input_4fold/4fold_valid.json
language: Chinese 
test_exists_labels: False

truncate_in_batch: True 
return_token_type_ids: False 
truncate_seq2seq_output: True

model_type: bert
model_name_or_path: ../../pretrain_model/roformer
hidden_size: 768
aggregation: none 

num_train_epochs: 5
max_seq_length: 512
dataloader_num_workers: 4

generation_max_length: 128
generation_num_beams: 4
predict_with_generate: True 
ignore_pad_token_for_loss: True 

per_device_train_batch_size: 16
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
# eval_accumulation_steps: 4
learning_rate: 5.0e-5
weight_decay: 1.0e-5
warmup_ratio: 0.1 
max_grad_norm: 1
optim: adamw_torch

load_best_model_at_end: True
metric_for_best_model: micro_f1 
greater_is_better: True 

logging_strategy: steps
logging_steps: 500
evaluation_strategy: epoch
eval_steps: 500
save_strategy: epoch
save_steps: 500
fp16: True

